- hosts: localhost
  tasks:
  - name: Ansible register with_items example
    shell: "find *.txt"
    args:
      chdir: "/var"
    register: with_output

  - shell: "cp {{ item }} {{item}}_bkp"
    with_items:
      - "{{ with_output.stdout_lines }}"
